# Nama Aplikasi
spring.application.name=lab-monitoring
server.port=8081

# Konfigurasi Koneksi PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_monitoring_db
spring.datasource.username=postgres
spring.datasource.password=MASUKKAN_PASSWORD_POSTGRES_ANDA

# Pengaturan JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
